name: Build and Push Backend to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Build com Gradle
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Configurar o Docker para Login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e Publicar a Imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-minikube:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/backend-minikube:latest ${{ secrets.DOCKER_USERNAME }}/backend-minikube:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-minikube:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-minikube:${{ github.sha }}
